trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azureorganization-key -Dsonar.projectKey=azureorganization-key_azureorganization-name -Dsonar.login=2c0a6ae5244dfd886468df6e57858f8146c206ac
  displayName: "Integrate SAST using SonarCloud to populate code coverage in Azure DevOps DevSecOps Pipeline"
